### ISSUE TITLE
Bug: Inconsistent UI in Home Page

### ISSUE THREAD

**Issue by sshsrn** [adityabindu/Hotel-Booking-Site#7]
In many places, the UI is inconsistent.

![image](https://user-images.githubusercontent.com/62781914/197383017-f1cccad0-6ae3-40de-b230-fbffe73cd2bf.png)
The Book now button is not even visible on seeing for the first time.

![image](https://user-images.githubusercontent.com/62781914/197383054-1818e3b1-b698-4508-b1f1-1db2a2dd0045.png)
Same is the case with the copyright text too.

**Comment by sshsrn** [comment]
@adityabindu Kindly assign me the issue as I would like to fix it.

**Comment by adityabindu** [comment]
@SSHSRN issue has been assigned, you can start working.
